print('hello world') 
print('hello world')
print('hello world')
print('Olgi777')
print('Olgi777')
print('Olgi777')
print('Olgi777')
print('Olgi777')
print('Olgi777')
print('Olgi777')
print('qqqq')
print('qqqq')
print('qqqq')
print('qqqq')
print('qqqq')
print('qqqq')
print('qqqq')

