CREATE TABLE IF NOT EXISTS orders(
    id INTEGER SERIAL PRIMARY KEY,
    user_id INTEGER FOREIGN KEY NOT NULL,
    status_id INTEGER FOREIGN KEY NOT NULL,
    FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);