CREATE TABLE IF NOT EXISTS order_items(
    id INTEGER SERIAL PRIMARY KEY,
    order_id INTEGER FOREIGN KEY,
    product_id INTEGER FOREIGN KEY,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);
