CREATE TABLE IF NOT EXISTS products(
    id INTEGER SERIAL PRIMARY KEY,
    title VARCHAR(36) NOT NULL,
    description VARCHAR(140) NOT NULL,
    category_id INTEGER FOREIGN KEY;
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,

);